### PR TITLE
feat: add partnership section to landing page

### LINKED ISSUE #94: Updated landing page to add partnership section
## Issue Overview

Update landing page in order to add new section for partnership

## Proposed Solutions or Ideas

- Implement this section based on provided [design](https://www.figma.com/design/GtsLINYwGOPcwYcz6nTXXa/The-Marquis-LP---OnlyDust?node-id=2496-3007&node-type=frame&t=mqhml2ySXWlrj7Eg-0)
- Make sure you follow the details and it works on mobile as well. 
image
- Update Discord link with this: https://discord.gg/ZWkWeypnzv

### PR DESCRIPTION
**Pull request by emarc99**
# Task name here

Fixes #94 

## Types of change

- [ ] Feature
- [ ] Bug
- [x ] Enhancement

### CODE REVIEW

**Comment by gianalarcon** [comment]
Hi Sir @emarc99 , how are you doing? Any updates on this pls?

**Comment by emarc99** [comment]
Just about to fix the mobile view and achieve the given UI for cards. 
Please, give me next 12 - 24 hours, then will open PR for review.
Thanks, sir.

**Comment by gianalarcon** [comment]
Hi Sir @emarc99 , how are you doing? Any updates on this pls?

**Comment by emarc99** [comment]
On it, sir.

**Pull request closed without merging**
