### PR TITLE
Fix minor issues on UI. Issue #96

### LINKED ISSUE #96: Fix minor issues on UI
## Issue Overview

- Fix alignment between error message and icon for every device on Login/Signup Page
- Fix alignment between active slide and another one, need to fix width, height, border-radius (Mobile)
- Color and text need to fix on LeaderBoard section
- Fix component "Invitation" match with Figma, also need to cover after login/signup page (PC, Table, Mobile)]
    - /signup/welcome
    - /login/welcome

## Proposed Solutions or Ideas
Pay attention to even the smallest details based on [Figma](https://www.figma.com/design/GtsLINYwGOPcwYcz6nTXXa/The-Marquis-LP---OnlyDust?node-id=0-1&node-type=canvas&t=i7Kp9hywq6eBKAso-0)

### PR DESCRIPTION
**Pull request by therealemino**
# Fix minor issues on UI

Fixes #96

## Types of change

- [ ] Feature
- [ ] Bug
- [x] Enhancement

### CODE REVIEW

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
- component "Invitation"
  - Referral Link bigger than Referral Code - PC verion (welcome page - both login/signup). On Mb version, the content should be center from screen, too much top postion for now
  - Width of each button function items too small, should be 44px on PC & Tablet, then 30px on MB
- GamesSlider still not match Figma on MB, need to fix alignment between active slide and another one

**Comment by therealemino** [comment]
@Buuh2511 please review

### Fixes:

#### Invitation Component
1. Social buttons sizes
2. Referral link and Referral  code fields
3. Centre content on mobile screens

#### GamesSlider
1. Mobile view alignment (centered).
2. Added Extra responsive screens to cater for larger and smaller mobile devices.

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
- Check again on /signup/welcome please, also on tablet.
- The content on /signup/welcome & /login/welcome should be center at every screen
- Game slider on MB fixed, but on PC the image has been cut off a bit and no longer has borderRadius

Error images :
Screenshot 2024-12-17 at 12 44 44 PM
Screenshot 2024-12-17 at 12 51 32 PM
Screenshot 2024-12-17 at 12 52 07 PM

**Comment by therealemino** [comment]
Hi @Buuh2511, apologies for the oversight on the signup invitation page. The fix has now been implemented

Fixes:
1. Centered content on /signup/welcome and /login/welcome across all screen sizes, including tablet & Desktop.  
2. Resolved image cut-off issue on GameSlider (PC).
3. Content width of /signup/invitation (tablet & PC).

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
- what is` "the-marquis-ui": "file:"` use for ?
- Need to fix margin on MB 
image

**Comment by Buuh2511** [comment]
> * what is` "the-marquis-ui": "file:"` use for ?
> * Need to fix margin on MB
>   image

After this minor issue have been fixed, can merge

**Comment by therealemino** [comment]
Hi, @Buuh2511 

- Pushed the minor fix for the margin
- The `"the-marquis-ui": "file:"`: VSCode automatically appends it to the package.json when I install the dependencies locally. I'm not sure what it's used for exactly but I know it's pointing to the root project's folder.

**Comment by therealemino** [comment]
@gianalarcon I think we can merge now 🚀

**Review by Buuh2511 — APPROVED** [review]

**Pull request merged**
