### PR TITLE
Improve current CI/CD

### LINKED ISSUE #90: Improve current CI/CD
## Issue Overview

Add Missing like run test, and more

## Proposed Solutions or Ideas

Outline your proposed solution or share any ideas you have for discussing or resolving the issue.

### PR DESCRIPTION
**Pull request by ncoquelet**
# Improve current CI/CD

Fixes #90 

## Types of change

- [x] Create a new workflow for contracts
    - [x] install scarb and snfoundry with software-mansion specific actions
    - [x] add `.tool-versions` to automaticaly share versions between devs and workflows
    - [x] steps for : check format, compile and test contracts
- [x] Improve NextJs workflow
    - [x] add step for run tests
    - [x] unify `yarn` usage
    - [x] install scarb with software-mansion specific actions
- [x] Both workflow continue to test formatting on both packages

### CODE REVIEW

**Comment by gianalarcon** [comment]
Looks good to me! Great job @ncoquelet . Please check here @Buuh2511

**Comment by ncoquelet** [comment]
I have try to add cairo-lint plugin, but its too early stage for moment and not yet compatible with last starknet contract syntax. Next time

**Comment by gianalarcon** [comment]
> cairo-lint plugin

Related to this [issue](https://github.com/software-mansion/cairo-lint/issues/169) right?

**Comment by ncoquelet** [comment]
> Related to this [issue](https://github.com/software-mansion/cairo-lint/issues/169) right?

Yes, I think they create the issue after reporting the it in thier TG

**Review by Buuh2511 — APPROVED** [review]

**Pull request merged**
