### PR TITLE
UI Web site: Fix Landing page and Fix Mobile responsive (Banner, sign-in/sign-up)

### LINKED ISSUE #74: UI Web site: Fix Landing page and Fix Mobile responsive (Banner, sign-in/sign-up)
### Landing Page

- Update Landing Page to match with provided design, pay attention to the details [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3179-5273&node-type=section&t=VbsLmNRi97qWmyNZ-0)

### Login/Signup Page
- Implement UI match with new Figma [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3179-5273&node-type=section&t=Ml3tHeDpoLpDEWyZ-0)

### Responsive
- Implement responsive Login/Signup page for Mobile [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3193-2257&node-type=section&t=VbsLmNRi97qWmyNZ-0)
- Implement responsive Login/Signup page for Tablet [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3179-8640&node-type=section&t=VbsLmNRi97qWmyNZ-0)
- Implement responsive Twitter invite post [here](https://www.figma.com/design/0p87o2YlDHHqXXjEdF2wUt/The-Marquis-(Only-Dust)?node-id=3158-5373&node-type=section&t=VbsLmNRi97qWmyNZ-0)

### Landing Page
- Fix based on provided design. Google play and app store logos
- Fix carousel : match size for active slide & inactive slide, make sure mobile version work well
- Fix align space between sections
- Fix effect at "Sign up now" button

### Login/Signup Page
- Fix based on new background

### Mobile responsive
- Fix based on provided design

### PR DESCRIPTION
**Pull request by melnikga**
# UI Web site: Fix Landing page and Fix Mobile responsive (Banner, sign-in/sign-up) #74

Fixes #74

## Types of change

- [x] Fix fonts and typography
- [x] Fix based on provided design. Google play and app store logos
- [x] Fix carousel : match size for active slide & inactive slide, make sure mobile version work well
- [x] Fix align space between sections
- [x] Fix effect at "Sign up now" button
- [x] Login/Signup Page
- [x] Login/Signup Page (Mobile)
- [x] Fix based on new background
- [x] Mobile responsive
- [x] Implement responsive Twitter invite post 

## Comments 
The first commit is a draft, not the final result of my work. I will continue working on this task.

### CODE REVIEW

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
1. Carousel work well on PC, but very bad on MB
2. Signup button effect (landing page) not match Figma and need to fix on MB
3. Need to fix alignment
image
4. This image does not match Figma
image
5. Need to fix alignment
image
6. Make the Star center line
image
7. Login/Signup Page do not match Figma, when switch between login & signup form have been moved on MB.

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
- Some not match Figma 
Screenshot 2024-11-28 at 10 25 56 AM
Screenshot 2024-11-28 at 10 23 51 AM
Screenshot 2024-11-28 at 10 21 56 AM
Screenshot 2024-11-28 at 10 19 56 AM
- "Sign up now" button still not really match Figma both PC and MB
- You should create new component for background login/signup page. Check /brandkit route plse. it've changed since u change  BackgroundGradient.tsx
- Just remove subcribe email address at Footer, we didnt change UI. Keep Footer in old version is ok
- Fix this pls 
Screenshot 2024-11-28 at 10 37 11 AM
Screenshot 2024-11-28 at 10 38 39 AM
- /invitation page should not allow scroll, keep everything in 100vh and QR code should work

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
- Fix /login/verification base on /signup/verification
- Fix wrong verify code modal on MB
- Fix MarquisMobile.tsx on MB
- Fix align base on Figma
image
- Fix inactive slide smaller
image

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
- **Tablet version look very bad**
- /login/verification & /signup/verification should be the same
- /invitation should not allow to scroll, not match Figma
- GameSlider not match Figma for now, make sure u tested before review. Pay your attentions detail in this part pls
- Sign up now button is nearly match Figma but still need to upgrade more. 
- Upgrade /signup/welcome & /login/welcome for MB

**Comment by Buuh2511** [comment]
Change the PR's title pls @melnikga

**Comment by Buuh2511** [comment]
> * **Tablet version look very bad**
> * /login/verification & /signup/verification should be the same
> * /invitation should not allow to scroll, not match Figma
> * GameSlider not match Figma for now, make sure u tested before review. Pay your attentions detail in this part pls
> * Sign up now button is nearly match Figma but still need to upgrade more.
> * Upgrade /signup/welcome & /login/welcome for MB

- **Errors UI**
image
image
image
image

**Comment by Buuh2511** [comment]
hi @melnikga any update on this ?

**Comment by melnikga** [comment]
Hi @Buuh2511 I'll add a new commit in the next couple of hours

**Comment by Buuh2511** [comment]
> Hi @Buuh2511 I'll add a new commit in the next couple of hours

yes, pay your attentions on detail and test before push a commit

**Comment by melnikga** [comment]
I'm almost done. I'm working on the adaptive layout for the welcome page, then I'll carefully check everything once more and send the commit.

**Comment by Buuh2511** [comment]
no need mt [here ](https://github.com/melnikga/themarquis-ui-sc/blob/8714787e31f7a9598856808ba0701329226d9d2a/packages/nextjs/components/Landingpage/MarquisMobile.tsx#L56)on MB
bugs UI
image
This does not match Figma, should not allow to scroll on MB
image
This also not match Figma
image

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
Need to change some minor bug on UI

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
- /signup/welcome
 - /login/welcome
 => max width content should be 326px on MB
 
 - very bad on Tablet, should not allow to scroll
image
- should be center
image

- GameSlider : spacing between slide not match Figma on PC
image

**Comment by Buuh2511** [comment]
Compare this 
image
to 
image
=> not match

Not match on Ipad 
image


Wrong spacing
image

Too much border radius
image


Need more spacing
image

**Review by Buuh2511 — CHANGES_REQUESTED** [review]
Still need to fix as a comment above

**Review by Buuh2511 — APPROVED** [review]

**Pull request merged**
